# Generated by Django 3.2.9 on 2021-12-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211208_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Arriving', 'Arriving'), ('Pending', 'Pending'), ('Packed', 'Packed'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EG', 'Electric Guitar'), ('AG', 'Acoustic Guitar'), ('CG', 'Classical Guitar'), ('M', 'Musical')], max_length=2),
        ),
    ]
